"""Initial migration

Revision ID: de4ce5d15def
Revises: 
Create Date: 2026-07-24 12:26:15.783544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de4ce5d15def'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.Enum('SCAN_TRIGGERED', 'SCAN_COMPLETED', 'SCREENSHOT_UPLOADED', 'SCREENSHOT_CONFIRMED', 'STATUS_CHANGED', 'FILTER_APPLIED', 'FILTER_REMOVED', 'CUTOFF_ENFORCED', 'VETO_APPLIED', name='audit_action_enum'), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('detail_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('daily_scans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('risk_bucket', sa.Enum('LOW', 'MODERATE', 'HIGH_RISK_HALO', name='risk_bucket_enum'), nullable=True),
    sa.Column('status', sa.Enum('PENDING_CONFIRMATION', 'CONFIRMED', 'LOCKED', name='scan_status_enum'), nullable=False),
    sa.Column('list_type', sa.Enum('LIST_1', 'LIST_2', name='list_type_enum'), nullable=True),
    sa.Column('factor_results_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('veto_rule', sa.String(length=50), nullable=True),
    sa.Column('veto_reason', sa.Text(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('strike_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_daily_scans_date_ticker', 'daily_scans', ['scan_date', 'ticker'], unique=True)
    op.create_index('ix_daily_scans_risk_bucket', 'daily_scans', ['risk_bucket'], unique=False)
    op.create_index(op.f('ix_daily_scans_scan_date'), 'daily_scans', ['scan_date'], unique=False)
    op.create_index('ix_daily_scans_status', 'daily_scans', ['status'], unique=False)
    op.create_index(op.f('ix_daily_scans_ticker'), 'daily_scans', ['ticker'], unique=False)
    op.create_table('market_data_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('endpoint', sa.String(length=200), nullable=False),
    sa.Column('params_hash', sa.String(length=64), nullable=False),
    sa.Column('response_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cached_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ttl_seconds', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_market_data_cache_lookup', 'market_data_cache', ['provider', 'endpoint', 'params_hash'], unique=True)
    op.create_table('factor_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('factor_id', sa.String(length=10), nullable=False),
    sa.Column('factor_name', sa.String(length=100), nullable=False),
    sa.Column('layer_number', sa.Integer(), nullable=False),
    sa.Column('triggered', sa.Boolean(), nullable=False),
    sa.Column('vetoed', sa.Boolean(), nullable=False),
    sa.Column('stubbed', sa.Boolean(), nullable=False),
    sa.Column('result_detail_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['daily_scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_factor_logs_factor_id', 'factor_logs', ['factor_id'], unique=False)
    op.create_index('ix_factor_logs_scan_factor', 'factor_logs', ['scan_id', 'factor_id'], unique=True)
    op.create_index(op.f('ix_factor_logs_scan_id'), 'factor_logs', ['scan_id'], unique=False)
    op.create_table('screenshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('storage_url', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('detected_price', sa.Float(), nullable=True),
    sa.Column('user_confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['daily_scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screenshots_scan_id'), 'screenshots', ['scan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screenshots_scan_id'), table_name='screenshots')
    op.drop_table('screenshots')
    op.drop_index(op.f('ix_factor_logs_scan_id'), table_name='factor_logs')
    op.drop_index('ix_factor_logs_scan_factor', table_name='factor_logs')
    op.drop_index('ix_factor_logs_factor_id', table_name='factor_logs')
    op.drop_table('factor_logs')
    op.drop_index('ix_market_data_cache_lookup', table_name='market_data_cache')
    op.drop_table('market_data_cache')
    op.drop_index(op.f('ix_daily_scans_ticker'), table_name='daily_scans')
    op.drop_index('ix_daily_scans_status', table_name='daily_scans')
    op.drop_index(op.f('ix_daily_scans_scan_date'), table_name='daily_scans')
    op.drop_index('ix_daily_scans_risk_bucket', table_name='daily_scans')
    op.drop_index('ix_daily_scans_date_ticker', table_name='daily_scans')
    op.drop_table('daily_scans')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
